### ISSUE TITLE
the formula at the line 307 in the FinCorrelation.py file is not correct

### ISSUE THREAD

**Issue by lajiiwang** [TSTK/ACHP#19]
cp_ha=cp_da/(1+W) #[J/kg_ha/K]

**Comment by lajiiwang** [comment]
I think the formular shoube be  cp_ha=cp_da + cp_water * W 
I don't know how to get the formular cp_ha=cp_da/(1+W)

**Comment by ibell** [comment]
I think its correct.  cp_da has units of J/kg_da/K, and 1+W has units of kg_ha/kg_da, therefore, cp_da*(1+W) has units of J/kg_ha/K .

**Comment by ibell** [comment]
Ooops, should have been cp_da/(1+W), same idea though.

**Comment by lajiiwang** [comment]
the unit is right,but
I have run the condenser.py separately, when run to the line 306 of FinCorrelations.py ,get ca_da = 1041.163; then run the next line,get cp_ha = cp_da/(1+w)=1041.163/(1+0.01821)=1022.533
so the heat capacity of humid air is smaller than the dry air, it's wrong.

**Comment by howardcheung** [comment]
The reason for the smaller number is due to the difference of mass involved with the two specific heat. To understand this, we can consider the two different mathematical expressions that we can write for the enthalpy change of a mass of humid air being heated at constant pressure. The first one is

m_a \delta h_a = m_a c_pa \delta T

where
m_a is the mass of _dry air_ inside the mass of _humid air_
\delta h_a is the enthalpy change per mass of _dry air_
c_pa is the specific heat of humid air per mass of _dry air_, **given by CoolProp**
\delta T is the temperature change

, and the second expression is

m_aw \delta h_aw = m_aw c_paw \delta T

where
m_a is the mass of _humid air_, including the mass of water vapor and dry air
\delta h_aw is the enthalpy change per mass of _humid air_
c_paw is the specific heat of humid air per mass of _humid air_, **which is the one we want for the calculation of the correlation**
\delta T is the temperature change

Since both expressions describe the total enthalpy change of the air in the process, they are equal. Considering that the temperature change is identical as well, one can write

m_aw c_paw = m_a c_pa

. Noticing that the mass of _humid air_ is related to that of its mass of _dry air_ by

m_aw = m_a (1+w)

where
w is the humidity ratio in kg of water vapor per kg of dry air

, the expression can be further simplified to

m_a (1+w) c_paw = m_a c_pa

and hence

c_paw = c_pa / (1+w)

as shown in the FinCorrelations.py. When we convert the specific heat of humid air from per mass of dry air to per mass of humid air, the amount of energy involved (the numerator part) does not change. The part that is changed is the amount of mass because we are including the mass of water vapor in addition to that of dry air. Hence the reduction of the specific heat. Do I answer your question?

**Comment by lajiiwang** [comment]
thank you for your explaination.It seems like right.
From line 307 of FinCorrelations.py,I ger  cp_da=1022.533 Kj/Kg.k ,the number is right,the physical meaning is 1kg humid air(0.982kg dry air add 0.018kg water vapor) absorb 1Kj heat energy when temperature inceases 1 degree,but what is the physical meaning of 1041.163 Kj/Kg.k get from line 306?
Can you explain for me?

**Comment by lajiiwang** [comment]
thank you for your explaination.It seems like right.
 From line 307 of FinCorrelations.py,I get cp_da=1022.533 Kj/Kg.k ,the number is right,the physical meaning is 1kg humid air(0.982kg dry air add 0.018kg water vapor) absorb 1Kj heat energy when temperature inceases 1 degree,but what is the physical meaning of 1041.163 Kj/Kg.k get from line 306?
 Can you explain for me?

**Comment by howardcheung** [comment]
1022.533kJ is the amount of energy needed to raise 1kg humid air with humidity ratio at 0.01833 kg of water per kg of dry air for 1K.

1041.163kJ is the amount of energy needed to heat up humid air that contains 1kg of dry air with humidity ratio at 0.01833 kg of water per kg of dry air for 1K. In other words, it's the energy needed to heat up 1.01833kg humid air with 1kg dry air for 1K. You can see that the masses of humid air involved in the two cases are different.

**Comment by lajiiwang** [comment]
the definition of specific enthalphy: the sum of  enthalpyh of 1kg dry air and the enthalphy of 0.001w (unit: kg) water vapor .
so the line 306 of FinCorrelations.py means the specific capacity per 1kg dry air added 0.001w water vapor,  line 307 means specific capacity per 1kg humid air.
so I think  line 306 can be changed to be cp_ha in the left of  equation best, not use cp_da.
because the result of  line 306 and 307 are humid air specific capacity, just the mass of humid air is different.
At the same time, I think you can replace the line306 and line307 with one setence below
cp_ha = HAPropsSI('cp','T',Inputs.Air.Tdb,'P',p,'W',W)

**Comment by lajiiwang** [comment]
line 296 of FinCorrelations.py should be changed to be following
# To convert a parameter from per kg_{dry air} to per kg_{humid air}, divide by (1+W)

**Comment by lajiiwang** [comment]
line 296 of FinCorrelations.py should be changed to be following

To convert a parameter from per kg_{dry air} to per kg_{humid air}, divide by (1+W)

**Comment by bo3mrh** [comment]
I guess this was originally implemented with the older version of CoolProps. @ibell can confirm the reason of using forward difference method for calculating cp_da.

**Comment by howardcheung** [comment]
Thanks for pointing out the typo. I made a pull request to correct the typo.

**Comment by bo3mrh** [comment]
Thank you, Howard
